dist: bionic
language: python
python: "3.10"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
services:
  - docker
env:
  global:
    - APPLICATION_NAME: gemini
    - CONTAINER: gemini
    - APPLICATION_PORT: 8006
before_install:
  - cp ${APPLICATION_NAME}/config.py.example ${APPLICATION_NAME}/config.py
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker-compose up -d
install:
  - ./wait-for-it.sh $CONTAINER:$APPLICATION_PORT -- docker-compose exec $CONTAINER pip install coverage
  - pip install "pre-commit===2.13.0" && pre-commit install
script:
  - pre-commit run --all-files --show-diff-on-failure
  - docker-compose exec $CONTAINER coverage run manage.py test
  - docker-compose exec $CONTAINER coverage report --omit=*/migrations/* -m
before_deploy:
  - if [ ! -d deploy_scripts ]; then git clone https://github.com/RockefellerArchiveCenter/deploy_scripts.git; fi
  - sudo deploy_scripts/substitute_env.sh
  - ./deploy_scripts/containers/push_image_to_ecr.sh
  - ./deploy_scripts/container/install_kubectl.sh
deploy:
  provider: script
  script: bash deploy_scripts/containers/deploy_image_k8s.sh
  on:
    repo: RockefellerArchiveCenter/${APPLICATION_NAME}
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(base|development)$
notifications:
  email: false
