language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
services:
  - docker
env:
  global:
    - APPLICATION_NAME: gemini
    - CONTAINER: gemini-web
    - DJANGO_PORT: 8006
before_install:
  - cp ${APPLICATION_NAME}/config.py.example ${APPLICATION_NAME}/config.py
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker-compose up -d
install:
  - ./wait-for-it.sh $CONTAINER:$DJANGO_PORT -- docker-compose exec $CONTAINER pip install coverage
  - pip install "pre-commit===2.13.0" && pre-commit install
script:
  - pre-commit run --all-files --show-diff-on-failure
  - docker-compose exec $CONTAINER coverage run manage.py test
after_script:
  - docker-compose exec $CONTAINER coverage report --omit=*/migrations/* -m
notifications:
  email: false
