version: '3'

services:
  gemini-db:
    image: postgres:10.4
    volumes:
      - geminidb:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - SQL_PASSWORD=postgres
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_HOST=gemini-db
  gemini-web:
    build: .
    image: ${CONTAINER:-gemini}
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8006:8006"
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8006}
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=gemini-db
    depends_on:
      - gemini-db

volumes:
  geminidb:
