version: '3'

services:
  gemini_db:
    image: postgres:10.4
    volumes:
      - geminidb:/var/lib/postgresql/data/
  gemini_web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8006:8006"
    depends_on:
      - gemini_db

volumes:
  geminidb:
