version: '3'

services:
  gemini-db:
    image: postgres:14.4
    volumes:
      - geminidb:/var/lib/postgresql/data/
  gemini-web:
    build: .
    entrypoint: /code/entrypoint.sh
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8006}
    volumes:
      - .:/code
    ports:
      - "${APPLICATION_PORT:-8006}:${APPLICATION_PORT:-8006}"
    depends_on:
      - gemini-db

volumes:
  geminidb:
