version: '3'

services:
  gemini-db:
    image: postgres:10.4
    volumes:
      - geminidb:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  gemini-web:
    build: .
    entrypoint: /code/entrypoint.sh
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8006}
    volumes:
      - .:/code
    ports:
      - "8006:8006"
    depends_on:
      - gemini-db

volumes:
  geminidb:
