# Generated by Django 2.0 on 2018-08-20 18:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('accession', 'Accession'), ('agent', 'Agent'), ('collection', 'Collection'), ('file', 'File'), ('object', 'Object'), ('rights', 'Rights'), ('term', 'Term')], max_length=50)),
                ('process_status', models.CharField(choices=[('10', 'Object updated in source'), ('50', 'Object updated in consumer')], max_length=50)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
