# Generated by Django 2.0.8 on 2018-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='process_status',
            field=models.CharField(choices=[(10, 'Package downloaded'), (20, 'Package stored')], default=10, max_length=50),
        ),
    ]
