# Generated by Django 3.2.4 on 2021-07-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storer', '0005_auto_20200317_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
