# Generated by Django 3.2.7 on 2021-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storer', '0006_alter_package_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='archivematica_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
