# Generated by Django 4.2.1 on 2023-06-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storer', '0007_package_archivematica_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='mimetypes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='origin',
            field=models.CharField(choices=[('aurora', 'Aurora'), ('legacy_digital', 'Legacy Digital Processing'), ('digitization', 'Digitization'), ('av_digitization', 'Audiovisual Digitization')], default='aurora', max_length=20),
        ),
    ]
