name: update actions dependencies
on:

  schedule:
    - cron:  '0 0 15 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: development
          persist-credentials: false

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          base: development
          branch: actions-dependency-updates
          delete-branch: true
          title: Actions Dependency Updates
          commit-message: Actions Dependency updates
